image: registry.gitlab.com/pages/hugo:0.58.2

test:
  script:
  - apk --update add git nodejs nodejs-npm
  - cd themes && git clone https://github.com/wet-boew/wet-boew-hugo.git wxt
  - cd ..
  - hugo
  except:
  - master

pages:
  script:
  - apk --update add git nodejs nodejs-npm
  - cd themes && git clone https://github.com/wet-boew/wet-boew-hugo.git wxt
  - cd ..
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
