BaseUrl: "https://drupalwxt.github.io"
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
LanguageCode: "en-us"
Title: "Drupal WxT"
PluralizeListTitles: False
menu:
  main:
    - Name: "WxT"
      Weight: -110
      Identifier: "wxt"
      URL: "/wxt/"
    - Name: "Releases for WxT"
      Parent: "wxt"
      Weight: -115
      URL: "/wxt/releases/"
    - Name: "Repositories for WxT"
      Parent: "wxt"
      Weight: -110
      URL: "/wxt/repositories/"
    - Name: "WxT Minimal Install"
      Parent: "wxt"
      Weight: -105
      Identifier: "minimalinstall"
      URL: "https://www.drupal.org/project/wxt/issues/3182208"
    - Name: "Upgrade Path from 3.0.x -> 4.0.x"
      Parent: "wxt"
      Weight: -100
      Identifier: "upgradepath"
      URL: "https://www.drupal.org/project/wxt/issues/3182648"
    - Name: "Roadmap"
      Parent: "wxt"
      Weight: -95
      Identifier: "roadmap"
      URL: "https://www.drupal.org/project/wxt/issues/3182977"
    - Name: "All WxT Entries"
      Parent: "wxt"
      Weight: -90
      URL: "/wxt/"
    - Name: "Installation"
      Weight: -95
      Identifier: "install"
      URL: "/wxt/"
    - Name: "Installation Profile"
      Parent: "install"
      Weight: -90
      Identifier: "drupal"
      URL: "https://drupal.org/project/wxt"
    - Name: "Composer Project"
      Parent: "install"
      Weight: -100
      Identifier: "composer"
      URL: "https://github.com/drupalwxt/site-wxt"
    - Name: "Composer Project Template"
      Parent: "install"
      Weight: -100
      Identifier: "project-template"
      URL: "https://github.com/drupalwxt/wxt-project"
    - Name: "Helm Chart for Kubernetes"
      Parent: "install"
      Weight: -95
      Identifier: "kubernetes"
      URL: "https://github.com/drupalwxt/helm-drupalwxt"
    - Name: "Docker Containers"
      Parent: "install"
      Weight: -90
      Identifier: "docker"
      URL: "https://hub.docker.com/r/drupalwxt/site-wxt"
    - Name: "Drupal Repository"
      Parent: "install"
      Weight: -85
      Identifier: "drupal"
      URL: "https://drupal.org/project/wxt"
    - Name: "Issue Queue"
      Parent: "install"
      Weight: -80
      Identifier: "issues"
      URL: "https://drupal.org/project/issues/wxt"
    - Name: "CHANGELOG.md"
      Parent: "install"
      Weight: -75
      Identifier: "changelog"
      URL: "https://github.com/drupalwxt/wxt/blob/4.0.x/CHANGELOG.md"
    - Name: "GitHub Actions"
      Parent: "install"
      Weight: -70
      Identifier: "actions"
      URL: "https://github.com/drupalwxt/wxt/actions"
    - Name: "GitHub Tarball"
      Parent: "install"
      Weight: -65
      Identifier: "tarball"
      URL: "https://github.com/drupalwxt/wxt/releases"
    - Name: "Documentation"
      Weight: -90
      Identifier: "docs"
      URL: "/docs/"
    - Name: "Coding Standards"
      Parent: "docs"
      Weight: -120
      URL: "/docs/code/"
    - Name: "Composer Workflow"
      Parent: "docs"
      Weight: -120
      URL: "/docs/composer/"
    - Name: "Frequently Asked Questions"
      Parent: "docs"
      Weight: -120
      URL: "/docs/faq/"
    - Name: "Modules Selection"
      Parent: "docs"
      Weight: -115
      URL: "/docs/modules/"
    - Name: "Sub Installation Profile"
      Parent: "docs"
      Weight: -115
      URL: "/docs/subprofile/"
    - Name: "Theme Workflow"
      Parent: "docs"
      Weight: -115
      URL: "/docs/theme/"
    - Name: "Blog"
      Weight: -85
      Identifier: "blog"
      URL: "/post/"
Params:
  Author: "William Hearn"
  Banner: "Providing succinct information on how to leverage Drupal WxT @ Web Experience Toolkit"
  DateForm: "2006-01-02"
  disqusShortname: "drupalwxt"
  GoogleAnalyticsUserID: "XXXX-XXXX-XXXX"
  Github: "drupalwxt/wxt"
  Search: "drupalwxt.github.io"
  ShowRelatedPost: True
  Slogan: "Documentation Site for Drupal WxT"
  SyntaxHighlightTheme: "monokai.min.css"
  Theme: "theme-wet-boew"
ignoreFiles: [
    "sample.md$",
]
Indexes:
  tag: "tags"
permalinks:
  post: /post/:year/:month/:day/:title/
MetadataFormat: "yaml"
module :
  imports :
    - disable : false
      path : wxt
      mounts :
        - source: content
          target: content
        - source: static
          target: static
        - source: layouts
          target: layouts
        - source: data
          target: data
        - source: assets
          target: assets
        - source: i18n
          target: i18n
        - source: archetypes
          target: archetypes
        - source : node_modules/@bower_components
          target : static/lib
markup:
  goldmark:
    renderer:
      unsafe: true
