BaseUrl: "https://drupalwxt.github.io"
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
LanguageCode: "en-us"
Title: "Drupal WxT"
PluralizeListTitles: False
menu:
  main:
    - Name: "WxT"
      Weight: -110
      Identifier: "wxt"
      URL: "/wxt/"
    - Name: "Releases for WxT"
      Parent: "wxt"
      Weight: -115
      URL: "/wxt/d8/releases/"
    - Name: "Modules for WxT"
      Parent: "wxt"
      Weight: -110
      URL: "/wxt/d8/modules/"
    - Name: "All WxT Entries"
      Parent: "wxt"
      Weight: -100
      URL: "/wxt/"
    - Name: "Roadmap"
      Weight: -95
      Identifier: "roadmap"
      URL: "/architecture/roadmap/"
    - Name: "Composer"
      Weight: -95
      Identifier: "composer"
      URL: "/workflow/composer/"
    - Name: "Blog"
      Weight: -90
      Identifier: "blog"
      URL: "/post/"
Params:
  Author: "William Hearn"
  Banner: "Providing succinct information on how to leverage Drupal WxT @ Web Experience Toolkit"
  DateForm: "2006-01-02"
  disqusShortname: "drupalwxt"
  GoogleAnalyticsUserID: "XXXX-XXXX-XXXX"
  Github: "wet-boew/wet-boew-drupal"
  Search: "drupalwxt.github.io"
  ShowRelatedPost: True
  Slogan: "Documentation Site for Drupal WxT"
  SyntaxHighlightTheme: "monokai.min.css"
  Theme: "theme-wet-boew"
Indexes:
  tag: "tags"
permalinks:
  post: /post/:year/:month/:day/:title/
MetadataFormat: "yaml"
