BaseUrl: "http://drupalwxt.github.io"
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
LanguageCode: "en-us"
Title: "Drupal WxT"
PluralizeListTitles: False
menu:
  main:
    - Name: "WxT"
      Weight: -110
      Identifier: "wxt"
      Url: "/wxt/"
    - Name: "Makefiles for WxT"
      Parent: "wxt"
      Weight: -110
      Url: "/wxt/make/"
    - Name: "Modules for WxT"
      Parent: "wxt"
      Weight: -110
      Url: "/wxt/modules/"
    - Name: "Releases for WxT"
      Parent: "wxt"
      Weight: -110
      Url: "/wxt/releases/"
    - Name: "Working Examples"
      Parent: "wxt"
      Weight: -110
      Url: "/wxt/working-examples/"
    - Name: "All WxT Entries"
      Parent: "wxt"
      Weight: -100
      Url: "/wxt/"
    - Name: "Architecture"
      Weight: -100
      Identifier: "architecture"
      Url: "/architecture/"
    - Name: "Content Staging"
      Parent: "architecture"
      Weight: -110
      Url: "/architecture/deployment/"
    - Name: "All Architecture Entries"
      Parent: "architecture"
      Weight: -100
      Url: "/architecture/"
    - Name: "Release Cycle / Updates"
      Parent: "architecture"
      Weight: -110
      Url: "/architecture/release-cycle/"
    - Name: "Libraries API"
      Parent: "architecture"
      Weight: -110
      Url: "/architecture/libraries-api/"
    - Name: "Drush Make + Site Install"
      Parent: "architecture"
      Weight: -110
      Url: "/architecture/drush-make/"
    - Name: "Community"
      Weight: -100
      Identifier: "community"
      Url: "/community/"
    - Name: "Office Hours"
      Parent: community
      Weight: -110
      Identifier: "office-hours"
      Url: "/community/office-hours/"
    - Name: "Roadmap"
      Parent: community
      Weight: -110
      Identifier: "roadmap"
      Url: "/community/roadmap/"
    - Name: "All Community Entries"
      Parent: "community"
      Weight: -100
      Url: "/community/"
    - Name: "Blog"
      Weight: -90
      Identifier: "blog"
      Url: "/post/"
    - Name: "Performance"
      Weight: -90
      Identifier: "performance"
      Url: "/performance/"
Params:
  Author: "William Hearn"
  Banner: "Providing succinct information on how to work with Drupal WxT 4.x for the Web Experience Toolkit!"
  DateForm: "2006-01-02"
  disqusShortname: "drupalwxt"
  GoogleAnalyticsUserID: "XXXX-XXXX-XXXX"
  Github: "wet-boew/wet-boew-drupal"
  Search: "drupalwxt.github.io"
  ShowRelatedPost: True
  Slogan: "Documentation Site for Drupal WxT"
  SyntaxHighlightTheme: "monokai.min.css"
  Theme: "theme-wet-boew"
Indexes:
  tag: "tags"
permalinks:
  post: /post/:year/:month/:day/:title/
MetadataFormat: "yaml"
